### PR TITLE
implement buddy/flee rate into api

### PR DESCRIPTION
**Pull request by jeff-wolff**

### CODE REVIEW

**Comment by yayramen** [comment]
Haha, I finally set up email notifications.

**Comment by jeff-wolff** [comment]
For sure. I'm probably gonna add new feature to the IV calculator... Basically so you can filter the results by the first appraisal line (66.7% - 80%, 82.2% - 100% ..), and eliminate the irrelevant results

**Comment by yayramen** [comment]
Oh, absolutely. I was going to do it, but I couldn't think of a good way to make it work as a UI, which is why I only included the best stat filter.

**Comment by jeff-wolff** [comment]
I like how PokeAssistant does it:
https://pokeassistant.com/main/ivcalculator

**Pull request merged**
